import type { ProjectionTheme } from './types'

const baseShadow = '0 2px 18px rgba(0,0,0,0.85)'

export const THEME_CLASSIC: ProjectionTheme = {
  id: 'classic',
  name: 'Clássico centro',
  fontFamily: '"Avenir Next", "Segoe UI", system-ui, sans-serif',
  lyricSizeVw: 5.2,
  titleSizeVw: 1.6,
  lyricColor: '#ffffff',
  titleColor: '#ffffff',
  titleOpacity: 0.45,
  fontWeight: 650,
  letterSpacingEm: 0.02,
  lineHeight: 1.2,
  textAlign: 'center',
  vertical: 'center',
  offsetXPct: 0,
  offsetYPct: 0,
  rotationDeg: 0,
  padXVw: 8,
  padYVh: 8,
  textShadow: '0 3px 28px rgba(0,0,0,0.75)',
  overlayGradient:
    'linear-gradient(to top, rgba(0,0,0,0.55) 0%, rgba(0,0,0,0.2) 45%, transparent 100%)',
  backgroundColor: '#000000',
  showTitle: true,
  showArtist: false,
  showLyrics: true,
  animation: 'fade',
  animationMs: 320,
  animationIntervalMs: 0,
}

export const THEME_LOWER_THIRD: ProjectionTheme = {
  id: 'lower-third',
  name: 'Lower third (sobre câmera)',
  fontFamily: '"Avenir Next", "Helvetica Neue", system-ui, sans-serif',
  lyricSizeVw: 4.2,
  titleSizeVw: 1.3,
  lyricColor: '#ffffff',
  titleColor: '#d7dde8',
  titleOpacity: 0.7,
  fontWeight: 600,
  letterSpacingEm: 0.01,
  lineHeight: 1.25,
  textAlign: 'center',
  vertical: 'bottom',
  offsetXPct: 0,
  offsetYPct: 0,
  rotationDeg: 0,
  padXVw: 6,
  padYVh: 7,
  textShadow: baseShadow,
  overlayGradient:
    'linear-gradient(to top, rgba(0,0,0,0.78) 0%, rgba(0,0,0,0.35) 55%, transparent 100%)',
  backgroundColor: '#000000',
  showTitle: false,
  showArtist: false,
  showLyrics: true,
  animation: 'slide-up',
  animationMs: 380,
  animationIntervalMs: 0,
}

export const THEME_BOLD: ProjectionTheme = {
  id: 'bold',
  name: 'Impacto',
  fontFamily: 'Impact, Haettenschweiler, "Arial Narrow Bold", sans-serif',
  titleFontFamily: '"Avenir Next", system-ui, sans-serif',
  lyricSizeVw: 5.6,
  titleSizeVw: 1.4,
  lyricColor: '#fff8e7',
  titleColor: '#ffd27a',
  titleOpacity: 0.85,
  fontWeight: 700,
  letterSpacingEm: 0.04,
  lineHeight: 1.1,
  textAlign: 'center',
  vertical: 'center',
  offsetXPct: 0,
  offsetYPct: 0,
  rotationDeg: 0,
  padXVw: 7,
  padYVh: 6,
  textShadow: '0 4px 0 rgba(0,0,0,0.55), 0 8px 32px rgba(0,0,0,0.65)',
  overlayGradient:
    'linear-gradient(to top, rgba(0,0,0,0.6) 0%, transparent 70%)',
  backgroundColor: '#050505',
  showTitle: true,
  showArtist: false,
  showLyrics: true,
  animation: 'fade',
  animationMs: 280,
  animationIntervalMs: 0,
}

export const THEME_SOFT_TOP: ProjectionTheme = {
  id: 'soft-top',
  name: 'Suave topo',
  fontFamily: 'Georgia, "Times New Roman", serif',
  lyricSizeVw: 3.8,
  titleSizeVw: 1.5,
  lyricColor: '#f4f1ea',
  titleColor: '#c9c2b4',
  titleOpacity: 0.8,
  fontWeight: 500,
  letterSpacingEm: 0.03,
  lineHeight: 1.35,
  textAlign: 'center',
  vertical: 'top',
  offsetXPct: 0,
  offsetYPct: 0,
  rotationDeg: 0,
  padXVw: 10,
  padYVh: 10,
  textShadow: '0 2px 16px rgba(0,0,0,0.7)',
  overlayGradient:
    'linear-gradient(to bottom, rgba(0,0,0,0.65) 0%, rgba(0,0,0,0.2) 50%, transparent 100%)',
  backgroundColor: '#0b0b0b',
  showTitle: true,
  showArtist: true,
  showLyrics: true,
  animation: 'slide-down',
  animationMs: 400,
  animationIntervalMs: 0,
}

export const BUILTIN_THEMES: ProjectionTheme[] = [
  THEME_CLASSIC,
  THEME_LOWER_THIRD,
  THEME_BOLD,
  THEME_SOFT_TOP,
]

export const DEFAULT_THEME = THEME_LOWER_THIRD

/** Tema padrão para texto bíblico (referência + versículos) */
export const DEFAULT_BIBLE_THEME: ProjectionTheme = {
  id: 'bible-serif',
  name: 'Bíblia (serif)',
  fontFamily: 'Georgia, "Times New Roman", serif',
  titleFontFamily: '"Avenir Next", system-ui, sans-serif',
  lyricSizeVw: 4.0,
  titleSizeVw: 1.5,
  lyricColor: '#f4f1ea',
  titleColor: '#c9c2b4',
  titleOpacity: 0.85,
  fontWeight: 500,
  letterSpacingEm: 0.01,
  lineHeight: 1.4,
  textAlign: 'center',
  vertical: 'center',
  offsetXPct: 0,
  offsetYPct: 0,
  rotationDeg: 0,
  padXVw: 10,
  padYVh: 10,
  textShadow: '0 2px 16px rgba(0,0,0,0.7)',
  overlayGradient:
    'linear-gradient(to top, rgba(0,0,0,0.55) 0%, rgba(0,0,0,0.2) 50%, transparent 100%)',
  backgroundColor: '#0b0b0b',
  showTitle: true,
  showArtist: false,
  showLyrics: true,
  wrapLines: true,
  animation: 'fade',
  animationMs: 320,
  animationIntervalMs: 0,
}

export const FONT_OPTIONS = [
  { id: 'avenir', label: 'Avenir Next', value: '"Avenir Next", "Segoe UI", system-ui, sans-serif' },
  { id: 'helvetica', label: 'Helvetica Neue', value: '"Helvetica Neue", Helvetica, Arial, sans-serif' },
  { id: 'sf', label: 'SF Pro', value: '-apple-system, BlinkMacSystemFont, "SF Pro Text", system-ui, sans-serif' },
  { id: 'futura', label: 'Futura', value: 'Futura, "Trebuchet MS", sans-serif' },
  { id: 'optima', label: 'Optima', value: 'Optima, Candara, sans-serif' },
  { id: 'gill', label: 'Gill Sans', value: '"Gill Sans", "Gill Sans MT", Calibri, sans-serif' },
  { id: 'georgia', label: 'Georgia', value: 'Georgia, "Times New Roman", serif' },
  { id: 'palatino', label: 'Palatino', value: 'Palatino, "Palatino Linotype", "Book Antiqua", serif' },
  { id: 'baskerville', label: 'Baskerville', value: 'Baskerville, "Times New Roman", serif' },
  { id: 'didot', label: 'Didot', value: 'Didot, "Bodoni MT", serif' },
  { id: 'impact', label: 'Impact', value: 'Impact, Haettenschweiler, sans-serif' },
  { id: 'copperplate', label: 'Copperplate', value: 'Copperplate, "Copperplate Gothic Light", fantasy' },
  { id: 'menlo', label: 'Menlo', value: 'Menlo, Monaco, Consolas, monospace' },
]

export const ANIMATION_OPTIONS: Array<{ id: ProjectionTheme['animation']; label: string }> = [
  { id: 'none', label: 'Nenhuma' },
  { id: 'fade', label: 'Fade' },
  { id: 'slide-up', label: 'Slide up' },
  { id: 'slide-down', label: 'Slide down' },
  { id: 'slide-left', label: 'Slide left' },
  { id: 'slide-right', label: 'Slide right' },
  { id: 'zoom-in', label: 'Zoom in' },
  { id: 'zoom-out', label: 'Zoom out' },
]
